# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class UserRecommendStub(object):
    """使用service定义一组远端服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserRecommend = channel.unary_unary(
                '/UserRecommend/UserRecommend',
                request_serializer=test__pb2.UserRequest.SerializeToString,
                response_deserializer=test__pb2.UserResponse.FromString,
                )


class UserRecommendServicer(object):
    """使用service定义一组远端服务
    """

    def UserRecommend(self, request, context):
        """使用rpc定义函数名 ()里是传入参数（只能打包为一个对象中） returns()括号里定义返回参数（只能打包为一个对象中）{}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserRecommendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserRecommend': grpc.unary_unary_rpc_method_handler(
                    servicer.UserRecommend,
                    request_deserializer=test__pb2.UserRequest.FromString,
                    response_serializer=test__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserRecommend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserRecommend(object):
    """使用service定义一组远端服务
    """

    @staticmethod
    def UserRecommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserRecommend/UserRecommend',
            test__pb2.UserRequest.SerializeToString,
            test__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
