# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"[\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x12\n\nchannel_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x61rticle_num\x18\x03 \x01(\x05\x12\x12\n\ntime_stamp\x18\x04 \x01(\x03\"\xf0\x01\n\x0cUserResponse\x12\x0f\n\x07\x65xposer\x18\x01 \x01(\t\x12\x12\n\ntime_stamp\x18\x02 \x01(\x03\x12)\n\nrecommends\x18\x03 \x03(\x0b\x32\x15.UserResponse.Article\x1a\x8f\x01\n\x07\x41rticle\x12\x12\n\narticle_id\x18\x01 \x01(\x03\x12*\n\x05track\x18\x02 \x01(\x0b\x32\x1b.UserResponse.Article.Track\x1a\x44\n\x05Track\x12\r\n\x05\x63lick\x18\x01 \x01(\t\x12\x0f\n\x07\x63ollect\x18\x02 \x01(\t\x12\r\n\x05share\x18\x03 \x01(\t\x12\x0c\n\x04read\x18\x04 \x01(\t2?\n\rUserRecommend\x12.\n\rUserRecommend\x12\x0c.UserRequest\x1a\r.UserResponse\"\x00\x62\x06proto3')



_USERREQUEST = DESCRIPTOR.message_types_by_name['UserRequest']
_USERRESPONSE = DESCRIPTOR.message_types_by_name['UserResponse']
_USERRESPONSE_ARTICLE = _USERRESPONSE.nested_types_by_name['Article']
_USERRESPONSE_ARTICLE_TRACK = _USERRESPONSE_ARTICLE.nested_types_by_name['Track']
UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), {

  'Article' : _reflection.GeneratedProtocolMessageType('Article', (_message.Message,), {

    'Track' : _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), {
      'DESCRIPTOR' : _USERRESPONSE_ARTICLE_TRACK,
      '__module__' : 'test_pb2'
      # @@protoc_insertion_point(class_scope:UserResponse.Article.Track)
      })
    ,
    'DESCRIPTOR' : _USERRESPONSE_ARTICLE,
    '__module__' : 'test_pb2'
    # @@protoc_insertion_point(class_scope:UserResponse.Article)
    })
  ,
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:UserResponse)
  })
_sym_db.RegisterMessage(UserResponse)
_sym_db.RegisterMessage(UserResponse.Article)
_sym_db.RegisterMessage(UserResponse.Article.Track)

_USERRECOMMEND = DESCRIPTOR.services_by_name['UserRecommend']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERREQUEST._serialized_start=14
  _USERREQUEST._serialized_end=105
  _USERRESPONSE._serialized_start=108
  _USERRESPONSE._serialized_end=348
  _USERRESPONSE_ARTICLE._serialized_start=205
  _USERRESPONSE_ARTICLE._serialized_end=348
  _USERRESPONSE_ARTICLE_TRACK._serialized_start=280
  _USERRESPONSE_ARTICLE_TRACK._serialized_end=348
  _USERRECOMMEND._serialized_start=350
  _USERRECOMMEND._serialized_end=413
# @@protoc_insertion_point(module_scope)
